// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.20.1
// source: models/protos/HotSearchService.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HotSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *HotSearchRequest) Reset() {
	*x = HotSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protos_HotSearchService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotSearchRequest) ProtoMessage() {}

func (x *HotSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_protos_HotSearchService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotSearchRequest.ProtoReflect.Descriptor instead.
func (*HotSearchRequest) Descriptor() ([]byte, []int) {
	return file_models_protos_HotSearchService_proto_rawDescGZIP(), []int{0}
}

func (x *HotSearchRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 热搜
type HotSearchModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Num  int32  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *HotSearchModel) Reset() {
	*x = HotSearchModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protos_HotSearchService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotSearchModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotSearchModel) ProtoMessage() {}

func (x *HotSearchModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_protos_HotSearchService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotSearchModel.ProtoReflect.Descriptor instead.
func (*HotSearchModel) Descriptor() ([]byte, []int) {
	return file_models_protos_HotSearchService_proto_rawDescGZIP(), []int{1}
}

func (x *HotSearchModel) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *HotSearchModel) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type HotSearchListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*HotSearchModel `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *HotSearchListResponse) Reset() {
	*x = HotSearchListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protos_HotSearchService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotSearchListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotSearchListResponse) ProtoMessage() {}

func (x *HotSearchListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_protos_HotSearchService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotSearchListResponse.ProtoReflect.Descriptor instead.
func (*HotSearchListResponse) Descriptor() ([]byte, []int) {
	return file_models_protos_HotSearchService_proto_rawDescGZIP(), []int{2}
}

func (x *HotSearchListResponse) GetData() []*HotSearchModel {
	if x != nil {
		return x.Data
	}
	return nil
}

//插入搜索
type InsertQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *InsertQueryRequest) Reset() {
	*x = InsertQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protos_HotSearchService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertQueryRequest) ProtoMessage() {}

func (x *InsertQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_protos_HotSearchService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertQueryRequest.ProtoReflect.Descriptor instead.
func (*InsertQueryRequest) Descriptor() ([]byte, []int) {
	return file_models_protos_HotSearchService_proto_rawDescGZIP(), []int{3}
}

func (x *InsertQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type InsertQueryRespense struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InsertQueryRespense) Reset() {
	*x = InsertQueryRespense{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_protos_HotSearchService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertQueryRespense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertQueryRespense) ProtoMessage() {}

func (x *InsertQueryRespense) ProtoReflect() protoreflect.Message {
	mi := &file_models_protos_HotSearchService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertQueryRespense.ProtoReflect.Descriptor instead.
func (*InsertQueryRespense) Descriptor() ([]byte, []int) {
	return file_models_protos_HotSearchService_proto_rawDescGZIP(), []int{4}
}

var File_models_protos_HotSearchService_proto protoreflect.FileDescriptor

var file_models_protos_HotSearchService_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x48, 0x6f, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x26,
	0x0a, 0x10, 0x48, 0x6f, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x36, 0x0a, 0x0e, 0x48, 0x6f, 0x74, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x43,
	0x0a, 0x15, 0x48, 0x6f, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x48,
	0x6f, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x2a, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22,
	0x15, 0x0a, 0x13, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x32, 0xa0, 0x01, 0x0a, 0x09, 0x48, 0x6f, 0x74, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x4b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x48, 0x6f, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x48, 0x6f, 0x74, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x46, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x1a, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_protos_HotSearchService_proto_rawDescOnce sync.Once
	file_models_protos_HotSearchService_proto_rawDescData = file_models_protos_HotSearchService_proto_rawDesc
)

func file_models_protos_HotSearchService_proto_rawDescGZIP() []byte {
	file_models_protos_HotSearchService_proto_rawDescOnce.Do(func() {
		file_models_protos_HotSearchService_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_protos_HotSearchService_proto_rawDescData)
	})
	return file_models_protos_HotSearchService_proto_rawDescData
}

var file_models_protos_HotSearchService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_models_protos_HotSearchService_proto_goTypes = []interface{}{
	(*HotSearchRequest)(nil),      // 0: models.HotSearchRequest
	(*HotSearchModel)(nil),        // 1: models.HotSearchModel
	(*HotSearchListResponse)(nil), // 2: models.HotSearchListResponse
	(*InsertQueryRequest)(nil),    // 3: models.InsertQueryRequest
	(*InsertQueryRespense)(nil),   // 4: models.InsertQueryRespense
}
var file_models_protos_HotSearchService_proto_depIdxs = []int32{
	1, // 0: models.HotSearchListResponse.data:type_name -> models.HotSearchModel
	0, // 1: models.HotSearch.GetHotSearchList:input_type -> models.HotSearchRequest
	3, // 2: models.HotSearch.InsertQuery:input_type -> models.InsertQueryRequest
	2, // 3: models.HotSearch.GetHotSearchList:output_type -> models.HotSearchListResponse
	4, // 4: models.HotSearch.InsertQuery:output_type -> models.InsertQueryRespense
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_protos_HotSearchService_proto_init() }
func file_models_protos_HotSearchService_proto_init() {
	if File_models_protos_HotSearchService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_protos_HotSearchService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protos_HotSearchService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotSearchModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protos_HotSearchService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotSearchListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protos_HotSearchService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_protos_HotSearchService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertQueryRespense); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_protos_HotSearchService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_protos_HotSearchService_proto_goTypes,
		DependencyIndexes: file_models_protos_HotSearchService_proto_depIdxs,
		MessageInfos:      file_models_protos_HotSearchService_proto_msgTypes,
	}.Build()
	File_models_protos_HotSearchService_proto = out.File
	file_models_protos_HotSearchService_proto_rawDesc = nil
	file_models_protos_HotSearchService_proto_goTypes = nil
	file_models_protos_HotSearchService_proto_depIdxs = nil
}
